version: "3"

services:
  db:
    image: mysql:8.0.24
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./.data/db:/var/lib/mysql
    environment: 
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      
  back:
    build: back/
    # rm -f tmp/pids/server.pidしとくとrailsのサーバ消し損ねたときに便利
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'" 
    volumes:
      - ./back:/app:cached
    depends_on:
      - db
    # ホストコンピュータのポート：Docker内のポート
    ports:
      - 3000:3000

  front:
    build: front/
    command: yarn run dev
    volumes: 
      - ./front:/app:cached
    ports:
      - 8080:3000
    depends_on:
      - back

volumes: 
  public-data:
  tmp-data:
  log-data:
  db-data:
